openwallet-foundation/sd-jwt-js

- CODEOWNERS
Issue: #2 
Add CODEOWNERS file in the root of the repo.
CODEOWNERS file contains 3 members of Hopae Inc.
> [#2]Add CODEOWNERS file

- examples/custom_header.ts
- examples/package.json
- src/index.ts
- src/type.ts
Issue: #26 
- Provide custom header in issue API
- Revise default jwt typ: `sd-jwt`
> [#26]Provide custom header in issue API

- examples/all.ts
- examples/basic.ts
- examples/custom.ts
- examples/custom_header.ts
- examples/decoy.ts
- examples/kb.ts
- examples/sdjwtobject.ts
- package.json
- src/index.ts
- src/test/index.spec.ts
- src/type.ts
- test/app-e2e.spec.ts
I fixed missing interface for custom signer and verifier.
Examples are applied.
update version to 2.0.1
> Fix: missing interface for custom signer and verifier

- packages/decode/src/decode.ts
- packages/decode/src/test/decode.spec.ts
- packages/node-crypto/src/crypto.ts
- packages/present/src/present.ts
- packages/present/src/test/present.spec.ts
- packages/types/src/type.ts
- packages/utils/src/disclosure.ts
Support sync functions for decode/present packages
- node digest helper function in `sd-jwt-node-crypto` changed to sync function
> Add sync functions for decode/present

- packages/broswer-crypto/package.json
- packages/core/package.json
- packages/decode/package.json
- packages/hash/package.json
- packages/node-crypto/package.json
- packages/present/package.json
- packages/types/package.json
- packages/utils/package.json
adding `publishConfig` with access:public
the no-private param only is to exclude private packages from being processed.
> fix: add publish config

- .github/workflows/build-test-publish-on-push-cached.yaml
- packages/browser-crypto/package.json
- packages/browser-crypto/src/crypto.ts
- packages/browser-crypto/src/test/crypto.spec.ts
- packages/node-crypto/src/test/crypto.spec.ts
adding the matrix testing approach allows us to test it for different versions
> Add matrix for testing

- examples/core-example/kb.ts
- packages/core/src/index.ts
- packages/core/src/sdjwt.ts
- packages/core/src/test/index.spec.ts
- packages/types/src/type.ts
sd_hash is a base64url hash digest of the presented SD-JWT. So we can calculate that value in our logic.
It closes #108
> feat: calcuate sd_hash in kb JWT

- examples/sd-jwt-example/README.md
- examples/sd-jwt-example/all.ts
- examples/sd-jwt-example/basic.ts
- examples/sd-jwt-example/custom.ts
- examples/sd-jwt-example/custom_header.ts
- examples/sd-jwt-example/decode.ts
- examples/sd-jwt-example/decoy.ts
- examples/sd-jwt-example/kb.ts
- examples/sd-jwt-example/package.json
- examples/sd-jwt-example/sdjwtobject.ts
- examples/sd-jwt-example/tsconfig.json
- examples/sd-jwt-example/utils.ts
- packages/core/README.md
- packages/core/package.json
- packages/core/src/index.ts
- packages/core/src/test/index.spec.ts
- packages/core/test/app-e2e.spec.ts
- packages/decode/src/test/decode.spec.ts
- packages/sd-jwt-vc/src/index.ts
- packages/sd-jwt-vc/src/sd-jwt-vc-payload.ts
- packages/sd-jwt-vc/src/test/index.spec.ts
- packages/sd-jwt-vc/test/app-e2e.spec.ts
- pnpm-lock.yaml
As discussed in #114 the sdjwtinstance should be non abstract to allow people to use it on its own.
I included the `validateReservedFields` function that will return nothing in the sdjwtinstance, but can be implemented in extended classes like `sdjwtvcinstance`. Doing so, we don't have to override the while isse function
Signed-off-by: Mirko Mollik <mirko.mollik@fit.fraunhofer.de>
> Make sdjwt instance non abstract

- package.json
- packages/core/src/index.ts
- packages/core/src/kbjwt.ts
- packages/core/src/test/index.spec.ts
- packages/core/src/test/kbjwt.spec.ts
- packages/node-crypto/src/crypto.ts
- packages/types/src/type.ts
- pnpm-lock.yaml
closes #125 
Adds signature verification to the kbVerify function. The whole payload of the actual token is passed to the kbverify function, it is not needed in the constructor of the KBJWT since this would break the extension from JWT.
The fetching of the key has to be implemented by the user. The payload has an optional field [cnf](https://datatracker.ietf.org/doc/html/rfc7800#section-3.2). The user is free to get the key from another field like `subject`, `id` etc. and is also free to parse the value - no limitation if there is a did url, jwk or url pointing to a hosted public key.<
Since we need to pass the payload to the verify function, the verify function in KBJWT will not get overwritten, but there will be a new function. It looks better to do it this way than adding an optional …
> Implement kbverify function

- packages/core/src/index.ts
- packages/core/src/test/index.spec.ts
In present method, when `presentationKeys` is undefined, then present all disclosures. but in this case kbjwt is not created.
I fixed it to create kbjwt.
> feat: create kb jwt when present all

- packages/core/src/jwt.ts
I found a bug while developing https://sdjwt.co
in jwt verify method, It doesn't wait until its resolved. verifier can be async function so we need await keyword.
> feat: fix async handling in jwt verify

- packages/core/src/test/index.spec.ts
- packages/types/src/type.ts
JsonWebKey type is in lib.dom.d.ts but some project might not want to include it tsconfig.json.
When I was trying to build credo-ts, It failed due to this. So I added it to our type file.
> feat: add jwk type

- packages/types/src/type.ts
I accidentally forgot to remove the rsa type.
> type: remove rsa type in jwk

- packages/present/src/present.ts
- packages/present/src/test/present.spec.ts
I made a selectDisclosures function to select serialized Disclosures with PresentationFrame.
I didn't know there would be a use case like this, but PEX needs this function.
@cre8  I'm planning to integrate it in PEX right away, if it's merged after review, will I be able to distribute it as 0.4.1?
> Feat: select disclosure for present

- .github/workflows/build-test-publish-on-push-cached.yaml
- packages/core/src/jwt.ts
- packages/core/src/kbjwt.ts
- packages/core/src/test/index.spec.ts
- packages/core/src/test/jwt.spec.ts
- packages/core/src/test/sdjwt.spec.ts
I added private field in JWT class. It is set when we created JWT instance from encoded.
And I created getUnsignedToken method to use encoded jwt string when it is existed.
It close #157
> fix: validate JWT signed other implemenation

- packages/sd-jwt-vc/src/index.ts
- packages/sd-jwt-vc/src/sd-jwt-vc-payload.ts
- packages/sd-jwt-vc/test/app-e2e.spec.ts
Improves alignment with draft 03
- iat is no longer required
- iat can now be selective disclosed
- the header.typ value is now vc+sd-jwt
> fix(sd-jwt-vc): improve alignment with draft-03

- .github/workflows/build-test-publish-on-push-cached.yaml
publish next step is incorrectly checking if the branch is `next` when the job only executes on the `main` branch causing publish next step to never execute
> fix: incorrect condition on workflow step

- packages/decode/src/decode.ts
- packages/decode/src/test/decode.spec.ts
the old `UnpackObj` function changes the input object. So I changed with clone logic and make old `unpackObj` rename to `unpackObjInternal`.
NOTE
- `unpackArray` function is not exported anymore. 
It closes #163
> feat: add clone ojbect logic in unpackObj

- packages/browser-crypto/README.md
- packages/core/README.md
- packages/decode/README.md
- packages/hash/README.md
- packages/node-crypto/README.md
- packages/present/README.md
- packages/sd-jwt-vc/README.md
- packages/types/README.md
- packages/utils/README.md
I changed old links connected to `next` branch to `main` branch
It closes #186
> doc: change link to main branch

- pnpm-lock.yaml
I revert #209 since it failed publish with lerna.
> fix: revert Bump vite from 5.2.9 to 5.2.10

- packages/sd-jwt-vc/src/sd-jwt-vc-instance.ts
- packages/sd-jwt-vc/test/app-e2e.spec.ts
The `kb` property is not being properly propagated in the `verify` function
> Fix KeyBinding not being propogated bug

- packages/sd-jwt-vc/src/sd-jwt-vc-instance.ts
Before we checked for equal, ignoring that the charset will be added. Using include solves this problem
Signed-off-by: Mirko Mollik <mirkomollik@gmail.com>
> fix: check if the header includes the string

- .github/workflows/release.yml
This fix should also push the tags that are required for a new release to github
Signed-off-by: Mirko Mollik <mirkomollik@gmail.com>
> fix: also push tags when releasing

- examples/sd-jwt-example/custom_header.ts
- examples/sd-jwt-vc-example/custom_header.ts
- packages/sd-jwt-vc/src/sd-jwt-vc-instance.ts
- packages/sd-jwt-vc/test/app-e2e.spec.ts
Draft 06 changes the media type from `vc+sd-jwt` to `dc+sd-jwt`.
https://author-tools.ietf.org/iddiff?url1=draft-ietf-oauth-sd-jwt-vc-05&url2=draft-ietf-oauth-sd-jwt-vc-06&difftype=--html
https://github.com/oauth-wg/oauth-sd-jwt-vc/pull/268
> feat: align media type with sd-jwt-vc draft 06

- examples/sd-jwt-example/flattenJSON.ts
- examples/sd-jwt-example/generalJSON.ts
- examples/sd-jwt-example/package.json
- packages/core/src/flattenJSON.ts
- packages/core/src/generalJSON.ts
- packages/core/src/index.ts
- packages/core/src/sdjwt.ts
- packages/core/src/test/flattenJSON.spec.ts
- packages/core/src/test/generalJSON.spec.ts
This PR implements [new JWS JSON serialization](https://www.ietf.org/archive/id/draft-ietf-oauth-selective-disclosure-jwt-13.html#name-jws-json-serialization) in standard.
Currently, I implemented the converting features. If you want, I can implement issue, present, and verify feature additionally on it. It may have dup code but I think it's quite simple approach for the first version since It doesn't ruin the original code. 
Perhaps I did a naive implementation or I might be wrong because I did not know the intended use cases of the standard. 
If there is anything you would like to point out, please feel free to do so. Thank you :)
> feat: add jws serialization feature

- .github/workflows/release.yml
The original script returns `pensivej: zustkeeper: lukasjhan: cre8`.
So I edited script to remove `:`
> ci: fix checking codeowner

- README.md
- docs/index.html
- packages/sd-jwt-vc/README.md
- packages/sd-jwt-vc/src/sd-jwt-vc-instance.ts
- packages/sd-jwt-vc/src/sd-jwt-vc-type-metadata-format.ts
- packages/sd-jwt-vc/src/test/vct.spec.ts
Draft 07 removes the `.well-known/vct/` addition to the `vct` URI when fetching the Type Metadata. Draft 08 is the latest.
> feat: align type metadata fetching with sd-jwt-vc draft 08

- biome.json
ignore lerna file for linting checks since it gets formatted and breaks the current rule.
Signed-off-by: Mirko Mollik <mirkomollik@gmail.com>
> chore: fix lerna lint error

- docs/0.x/sdjwt-instance.md
- examples/sd-jwt-example/all.ts
- examples/sd-jwt-example/basic.ts
- examples/sd-jwt-example/custom.ts
- examples/sd-jwt-example/custom_header.ts
- examples/sd-jwt-example/decoy.ts
- examples/sd-jwt-vc-example/all.ts
- examples/sd-jwt-vc-example/basic.ts
- examples/sd-jwt-vc-example/custom.ts
- examples/sd-jwt-vc-example/custom_header.ts
- examples/sd-jwt-vc-example/decoy.ts
- package.json
- packages/browser-crypto/src/crypto.ts
- packages/core/src/index.ts
- packages/core/test/app-e2e.spec.ts
- packages/hash/src/test/sha256.spec.ts
- packages/node-crypto/src/crypto.ts
- packages/present/src/test/present.spec.ts
- packages/sd-jwt-vc/README.md
- packages/sd-jwt-vc/src/test/index.spec.ts
- packages/sd-jwt-vc/src/test/vct.spec.ts
- packages/sd-jwt-vc/test/app-e2e.spec.ts
- packages/types/src/type.ts
Closes #264
Renaming `SHA-256` to `sha-256` to be compliant with iana naming as described in the issue.
I also added the type based on the iana values so autocomplete should warn the user when they use a wrong value and we are checking it during issuance (we do not this during decoding in case the sd jwt was created by another tool, ignoring these rules)
> chore: lowercase sha algorithm to be compliant

- packages/sd-jwt-vc/src/sd-jwt-vc-config.ts
- packages/sd-jwt-vc/src/sd-jwt-vc-instance.ts
Improve the fetch function based on the input from #258 + adding with timeout case and allowing to adjust the timeout value
> chore: improve error handing for fetch function

- packages/core/src/index.ts
- packages/types/src/type.ts
Noticed that PR #266 can be improved a bit. It is possible to utilise Typescript's [const assertion](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions) and derive the `HashAlgorithm` type from the `IANA_HASH_ALGORITHMS` array, making it unnecessary to duplicate the algorithm list for both the type and the run-time array. This requires moving the `IANA_HASH_ALGORITHMS` array to the `types` package and exporting it from there.
> type: define IANA hash algorithm list once

- examples/sd-jwt-example/generalJSON.ts
Hello! I noticed a typo in the sd-jwt generalJSON example logs while using the feature. 
I corrected 'flattenJSON(credential):' to 'generalJSON(credential)'.
Thank you for creating such a valuable library! :)
> chore: fix typo

- packages/types/src/type.ts
Types such as the following currently fail when trying to make the nested fields selectively discloseable:
```ts
type PID = {
given_name: string;
address?: {
country: string;
}
};
const disclosureFrame: DisclosureFrame<PID> = {
_sd: ['given_name'],
address: {
_sd: ['country']
}
};
```
Signed-off-by: Stefan Charsley <charsleysa@gmail.com>
> fix: Frame fails when a type with an optional or nullable field is used

- examples/sd-jwt-example/generalJSON.ts
- packages/core/src/flattenJSON.ts
- packages/core/src/generalJSON.ts
- packages/core/src/index.ts
- packages/core/src/test/flattenJSON.spec.ts
- packages/core/src/test/generalJSON.spec.ts
I fixed bug for encoding flattenJSON and generalJSON and tests to check this feature is correct.
It used to return (with two ~) when there is no disclosure and kbjwt like:
```
'eyJ0eXAiOiJzZCtqd3QiLCJhbGciOiJFUzI1NiJ9.eyJpZCI6IjEyMzQiLCJfc2QiOlsiYkRUUnZtNS1Zbi1IRzdjcXBWUjVPVlJJWHNTYUJrNTdKZ2lPcV9qMVZJNCIsImV0M1VmUnlsd1ZyZlhkUEt6Zzc5aGNqRDFJdHpvUTlvQm9YUkd0TW9zRmsiLCJ6V2ZaTlMxOUF0YlJTVGJvN3NKUm4wQlpRdldSZGNob0M3VVphYkZyalk4Il0sIl9zZF9hbGciOiJzaGEtMjU2In0.n27NCtnuwytlBYtUNjgkesDP_7gN7bhaLhWNL4SWT6MaHsOjZ2ZMp987GgQRL6ZkLbJ7Cd3hlePHS84GBXPuvg~~';
```
and it's fixed correctly :)
> feat: fix encoding bug for flattenJSON and generalJSON

- docs/index.html
Having the "Documentation" link point at the documentation of this library instead of [another deprecated library](https://www.npmjs.com/package/@hopae/sd-jwt).
> doc: Improve the Documentation link

- packages/sd-jwt-vc/src/sd-jwt-vc-type-metadata-format.ts
Adding [Display Metadata](https://www.ietf.org/archive/id/draft-ietf-oauth-sd-jwt-vc-09.html#name-display-metadata) and [Claim Metadata](https://www.ietf.org/archive/id/draft-ietf-oauth-sd-jwt-vc-09.html#name-claim-metadata) to the library.
@lukasjhan we should discuss how much functions we want to provide to deal with the information, like adding a function to return the rendered SVG, ect.  Right now I only added the types to it.
> WIP: feat: add missing types

- examples/sd-jwt-vc-example/all.ts
- examples/sd-jwt-vc-example/basic.ts
- examples/sd-jwt-vc-example/custom.ts
- examples/sd-jwt-vc-example/custom_header.ts
- examples/sd-jwt-vc-example/decoy.ts
- examples/sd-jwt-vc-example/kb.ts
- packages/core/src/index.ts
- packages/core/src/jwt.ts
- packages/core/src/test/index.spec.ts
- packages/core/src/test/jwt.spec.ts
- packages/core/test/app-e2e.spec.ts
- packages/jwt-status-list/README.md
- packages/jwt-status-list/src/test/status-list-jwt.spec.ts
- packages/sd-jwt-vc/README.md
- packages/sd-jwt-vc/src/sd-jwt-vc-instance.ts
- packages/sd-jwt-vc/src/test/index.spec.ts
- packages/sd-jwt-vc/src/test/vct.spec.ts
- packages/sd-jwt-vc/test/app-e2e.spec.ts
closes #291 
Extending the validation of `iat`, `exp` and `nbf`. It is possible to pass a custom timestamp to the verify function.
We are not blocking credentials that will be issued with an `iat` value that is in the future, so the issuer has full control over it.
> validate timestamp and set custom date

- docs/0.x/keybinding.md
- docs/0.x/sdjwt-instance.md
- docs/0.x/verify.md
- examples/sd-jwt-example/all.ts
- examples/sd-jwt-example/basic.ts
- examples/sd-jwt-example/custom.ts
- examples/sd-jwt-example/flattenJSON.ts
- examples/sd-jwt-example/generalJSON.ts
- examples/sd-jwt-example/kb.ts
- examples/sd-jwt-vc-example/all.ts
- examples/sd-jwt-vc-example/basic.ts
- examples/sd-jwt-vc-example/custom.ts
- examples/sd-jwt-vc-example/kb.ts
- packages/core/src/index.ts
- packages/core/src/jwt.ts
- packages/core/src/kbjwt.ts
- packages/core/src/test/kbjwt.spec.ts
- packages/sd-jwt-vc/src/sd-jwt-vc-instance.ts
closes #296 
since we are adding more and more configurable parameters to the verify function, it was moved to an object.
This will cause a breaking change, but will make the changes easier in the future.
> Add Verifier options

- examples/sd-jwt-example/kb.ts
Fix the SD-JWT key binding example to run without errors.
The example was failing with `SDJWTException: Missing required claim
keys: ssn` because:
- Only `id` was presented in the SD-JWT
- But verification required both `ssn` and `id`
Changed `requiredClaimKeys` from `['ssn', 'id']` to `['id']` to match the presented claim.
Now the example runs successfully and demonstrates proper SD-JWT verification with key binding.
> fix: correct requiredClaimKeys in sd-jwt kb example to match presented claims
