openwallet-foundation/sd-jwt-js

MAINTAINERS.md

Issue: #3 
Add MAINTAINERS.md
Refer to https://tac.openwallet.foundation/governance/maintainers-file-content/

[#3]Add MAINTAINERS.md

---

README.md
package.json

Issue: #9 
Add license in package.json
Add author in package.json
Add keywords in package.json
Fix typo in README.md

Add license in package.json

---

SECURITY.md

[#11]Add security.md

---

README.md

Issue: #13 
Fix typo package name

[#13]Fix typo in README

---

.github/workflows/test-pr.yaml

Issue: #18 
Add PR testing script to run test for every PR

[#18]Add PR testing script

---

.gitignore
README.md
package.json

Issue: #21 
Add measuring test coverage using jest
Current test coverage is 91% at #15

[#21]Add measuring test coverage

---

README.md

Issue: #21 
Fix badge URL. We can't use % directly. `%25` is correct value

[#21]Fix badge URL

---

package.json
src/crypto-browser.ts
src/crypto.ts
src/jwt.ts
src/type.ts

Fix browser support
- Change the signature's type to string(base64url)
- Create browser-crypto file for polyfill
- Add broswer configuration in package.json

Fix browser support

---

README.md
package.json

Rename package to `@hopae/sd-jwt` after #24
**Note:** Additional task
- Rename package name in wiki

Rename zhzlabs to hopae

---

src/sdjwt.ts

Issue: #35 
Fix Bug: Add keybinding when present.

[#35]Add keybinding when present

---

package.json

Issue: #28 
Add links to npm(package.json)
1. github repo link
2. issue link
3. docs(wiki) link

[#28]Add github link to npm

---

examples/kb.ts
examples/package.json

Issue: #30 
Add key binding example. I already add description in wiki

[#30]Add key binding example

---

README.md

Issue: #32 
Add badges in README.md and increase coverage to 93%

[#32]Add more badges in README

---

package.json

Change version for release v1.1.0

Release: v1.1.0

---

README.md
examples/kb.ts
src/index.ts
src/jwt.ts
src/kbjwt.ts
src/sdjwt.ts
src/test/index.spec.ts
src/test/jwt.spec.ts
src/test/kbjwt.spec.ts
src/type.ts
test/app-e2e.spec.ts

Issue: #45
Add features for v2.0:
- Support 07 version of standard
- revise verify, validate return type (boolean -> { header, payload }
- support custom signer, verifier function

Support 07 version of standard and new features for v2.0

---

examples/kb.ts
src/index.ts
src/test/index.spec.ts
src/type.ts

Issue: #49
I moved generating option from issue to present.
Provide custom signer function is now added.
NOTE: I fixed example as well

[#49]fix: generate key binding jwt in present

---

package.json

release: version 2.0

---

CODEOWNERS

chore: Add maintainer: berendsliedrecht

---

MAINTAINERS.md

Signed-off-by: Berend Sliedrecht <sliedrecht@berend.io>

chore: added Berend Sliedrecht to maintainers

---

README.md

Updating the readme to match with the latest commits.

fix; add vitest reference for testing

---

.github/workflows/build-test-publish-on-push-cached.yaml

integrated the covecov action. Not sure at this point if this works since it's not directly connected with any token to their platform
closes #69

fix: upload code cov

---

package.json
vitest.shared.js

closes: #76 #78 
adding e2e.spec.ts to vitest.
Example folder still in the coverage report included...

include e2e tests

---

package.json

add `--no-private` flag since npmjs default setting is private

fix: add public param

---

CODEOWNERS

@cre8 I added you as CODEOWNER. It makes you a reviewer of PRs

chore: add Mirko to the CODEOWNER

---

packages/core/src/sdjwt.ts

I added the comments of array disclosure logic to help developer understand :)

chore: Add description of array disclosure logic

---

packages/utils/src/test/disclosure.spec.ts

I added sync version tests for disclosure sync functions

test: add disclosure sync tests

---

.github/settings.yml

Closes: #112
Signed-off-by: Mirko Mollik <mirko.mollik@fit.fraunhofer.de>

Set protection rules for main and next

---

README.md
docs/index.html

I added [online debugger](https://sdjwt.co) in https://sdjwt.js.org

doc: add online debugger

---

README.md
docs/index.html

I added description of sd-jwt vc to our homepage.
I wrote a simple one based on what @cre8 wrote in the readme. :)
If there is anything you would like to write more about, please let me know.

doc: Add the sd-jwt vc description in sdjwt.js.org

---

README.md
docs/index.html

I updated Readme and docs to new version of standard.
sd-jwt: 08
sd-jwt-vc: 03

doc: update standard version

---

docs/0.x/claims.md
docs/0.x/keybinding.md
docs/0.x/present.md
docs/0.x/sdjwt-instance.md
docs/README.md
examples/present-example/present.ts
examples/sd-jwt-example/all.ts
examples/sd-jwt-example/basic.ts
examples/sd-jwt-example/custom.ts
examples/sd-jwt-example/kb.ts
examples/sd-jwt-vc-example/all.ts
examples/sd-jwt-vc-example/basic.ts
examples/sd-jwt-vc-example/custom.ts
examples/sd-jwt-vc-example/kb.ts

After #138, I updated docs and examples for presentationFrame.
And fix some minor typos :)

feat: update present example

---

.github/workflows/sync-next-with-latest.yml
lerna.json

this action will open a PR to next so a release that was generated on main will be synced with next

chore(ci): merge from main into next

---

packages/present/src/present.ts

I miss this export keyword. It need to be used in PEX

fix: add missing export

---

lerna.json
packages/browser-crypto/package.json
packages/core/package.json
packages/decode/package.json
packages/hash/package.json
packages/node-crypto/package.json
packages/present/package.json
packages/sd-jwt-vc/package.json
packages/types/package.json
packages/utils/package.json

Some reason the `pnpm biome ci .` failed today. I fixed it to pass

chore: fix lint

---

README.md

I added the npm download count in our README :)

doc: add npm download count in README

---

lerna.json
packages/browser-crypto/package.json
packages/core/package.json
packages/decode/package.json
packages/hash/package.json
packages/node-crypto/package.json
packages/present/package.json
packages/sd-jwt-vc/package.json
packages/types/package.json
packages/utils/package.json

ci: fix biome

---

packages/core/src/decoy.ts
packages/core/src/index.ts
packages/core/src/jwt.ts
packages/core/src/kbjwt.ts
packages/core/src/test/decoy.spec.ts
packages/decode/src/decode.ts
packages/utils/src/base64url.ts
packages/utils/src/disclosure.ts
packages/utils/src/test/base64url.spec.ts
packages/utils/src/test/disclosure.spec.ts

I updated convention of base64url related functions.
This will be a breaking changes on @sd-jwt/utils. Maybe applied PEX but It's not merged yet, So It will be fine.
It will close #178

fix: base64url convention

---

README.md

I added missing package: @sd-jwt/present in npm download badge.

doc: add missing present package

---

README.md

I changed npm download count to show by month.

doc: change npm download monthly

---

.github/workflows/build-test-publish-on-push-cached.yaml
.github/workflows/release.yml
pnpm-lock.yaml

@cre8 About #213, How about trying this change?

ci: fix pnpm install change lockfile during ci

---

examples/sd-jwt-example/all.ts

Uses the wrong jwt, presents the private Cred when it should use the public presentation

Update example/ all.ts

---

.github/workflows/release.yml
biome.json
package.json

Let lerna push directly, biome config needs to be updated later
Signed-off-by: Mirko Mollik <mirkomollik@gmail.com>

fix: push changes

---

packages/types/src/type.ts

ci: fix failing lint checking

---

README.md
docs/index.html

Update support statement for sdjwt 17

chore: update support statement for sdjwt 17

---

packages/core/src/sdjwt.ts
packages/sd-jwt-vc/src/sd-jwt-vc-instance.ts
packages/sd-jwt-vc/src/test/vct.spec.ts

SD JWT Instances VCT Metadata get separated from verify

---

packages/sd-jwt-vc/src/index.ts

Expose missing types based on this: https://github.com/openwallet-foundation/sd-jwt-js/pull/289
Signed-off-by: Mirko Mollik <mirko.mollik@eudi.sprind.org>

fix: expose types

---

packages/core/src/index.ts

closes #302
Signed-off-by: Mirko Mollik <mirko.mollik@eudi.sprind.org>

fix: pass required options parameter

---

packages/core/src/index.ts
packages/sd-jwt-vc/src/sd-jwt-vc-instance.ts
packages/sd-jwt-vc/src/test/index.spec.ts
packages/sd-jwt-vc/src/test/vct.spec.ts

Reverts openwallet-foundation/sd-jwt-js#308

Revert "Fix/248"

---

package.json
packages/browser-crypto/package.json
packages/core/package.json
packages/decode/package.json
packages/hash/package.json
packages/jwt-status-list/package.json
packages/node-crypto/package.json
packages/present/package.json
packages/sd-jwt-vc/package.json
packages/types/package.json
packages/utils/package.json

Sets the correct url to fix the publish process
Signed-off-by: Mirko Mollik <mirko.mollik@eudi.sprind.org>

fix: set correct url in package json
